sylius_ui:
    events:
        sylius.shop.layout.topbar:
            blocks:
                security_widget:
                    template: "@SyliusUserImpersonatorPlugin/Layout/Topbar/_securityWidget.html.twig"
                    priority: 10
        sylius.shop.checkout.header:
            blocks:
                header:
                    template: "@SyliusUserImpersonatorPlugin/Checkout/_header.html.twig"
                    priority: 10
        sylius.admin.channel.form.second_column_content:
            blocks:
                look_and_feel:
                    template: '@SyliusUserImpersonatorPlugin/Channel/Form/_lookAndFeel.html.twig'
                    priority: 10
