sylius_ui:
    events:
        sylius.shop.layout.topbar:
            blocks:
                user_impersonate_hint:
                    template: "@SyliusUserImpersonatorPlugin/Layout/Topbar/_user_impersonator_hint.html.twig"
                    priority: 15
        sylius.admin.channel.form.second_column_content:
            blocks:
                user_impersonate_settings:
                    template: '@SyliusUserImpersonatorPlugin/Channel/Form/_user_impersonate_settings.html.twig'
