services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true 
    
    Evo\SyliusUserImpersonatorPlugin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            
    Evo\SyliusUserImpersonatorPlugin\EventListener\ImpersonateUserListener:
        tags: 
            - { name: kernel.event_listener, event: sylius.user.security.impersonate }
    
    Evo\SyliusUserImpersonatorPlugin\EventListener\LogoutListener:
        tags:
            - name: 'kernel.event_listener'
    
    Evo\SyliusUserImpersonatorPlugin\ContextProvider\UserImpersonateHintContextProvider:
        tags:
            - { name: sylius.ui.template_event.context_provider } 
