services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true 
    
    Evo\SyliusUserImpersonatorPlugin\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
