services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true 
    
    Evo\SyliusUserImpersonatorPlugin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
    Evo\SyliusUserImpersonatorPlugin\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
        
    Evo\SyliusUserImpersonatorPlugin\EventListener\ImpersonateUserListener:
        tags: 
            - { name: kernel.event_listener, event: sylius.user.security.impersonate }
    
    Evo\SyliusUserImpersonatorPlugin\EventListener\LogoutListener:
        tags:
            - name: 'kernel.event_listener'
